#!/bin/bash
vol=$(pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')
mute=$(pacmd list-sinks | awk '/muted/ { print $2 }')
if [[ $mute == *"yes"* ]];
then
	printf " "
else 
	printf " "
        printf $vol
fi
