#!/bin/sh

getopts "dims:" FLAG
case "$FLAG" in
	d)
		pactl set-sink-volume @DEFAULT_SINK@ -5%
		kill -44 $(pidof dwmblocks);;
	i)
		(( $[ $(pactl get-sink-volume @DEFAULT_SINK@ | grep -Po '\d+(?=%)' | head -n 1) + 5 ] > 100 )) && \
		pactl set-sink-volume @DEFAULT_SINK@ 100% || \
		pactl set-sink-volume @DEFAULT_SINK@ +5%
		kill -44 $(pidof dwmblocks);;
	m)
		pactl set-sink-mute @DEFAULT_SINK@ toggle
		kill -44 $(pidof dwmblocks);;
	s)
		VOLUME=$2
		(( VOLUME < 0 )) && VOLUME=0
		(( VOLUME > 100 )) && VOLUME=100
		pactl set-sink-volume @DEFAULT_SINK@ $VOLUME%
		kill -44 $(pidof dwmblocks);;
	*)
		VOLUME=$(pactl get-sink-volume @DEFAULT_SINK@ | grep -Po '\d+(?=%)' | head -n 1)
		MUTE=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')
		if [[ $MUTE == *"yes"* ]];
		then
			echo "MUTE"
		else 
			echo "$VOLUME"
		fi

esac
