#!/bin/sh
vol=$(pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')
if (( $vol <= 95 )); then
	pactl set-sink-volume 0 +5%
	pactl set-sink-volume 1 +5%
	pactl set-sink-volume 2 +5%
	pactl set-sink-volume 3 +5%
else
	pactl set-sink-volume 0 100%
	pactl set-sink-volume 1 100%
	pactl set-sink-volume 2 100%
	pactl set-sink-volume 3 100%
fi
kill -44 $(pidof dwmblocks)
